on:
  workflow_run:
    workflows: [Lexical Core Tests]
    types: [completed]

jobs:
  # on-failure:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo '${{ github.event.workflow_run.display_title }}'
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
