name: Flaky Test Tracker Notice

on:
  workflow_run:
    workflows: [Lexical Core Tests]
    types:
      - completed

jobs:
  # on-failure:
  on-success:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo '${{ github.event.workflow_run.display_title }}'
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            E2E tests has a failure. Please check if the failure is due to a flaky test. 
            Visit the [Flaky Test Tracker](https://github.com/facebook/lexical/discussions/6289) for known flaky tests, 
            and record the failed test run there if its a flaky failure.
